// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

type Event struct {
	EventID         string
	SchemaVersion   int64
	Provider        string
	Surface         string
	Repo            string
	Project         string
	CostTag         string
	Model           string
	TsStartUnixnano int64
	EventJson       string
}

type ScanMetum struct {
	Provider string
	LastScan int64
}
