// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	GetEvent(ctx context.Context, eventID string) (string, error)
	GetLastScan(ctx context.Context, provider string) (int64, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]string, error)
	SetLastScan(ctx context.Context, arg SetLastScanParams) error
	UpsertEvent(ctx context.Context, arg UpsertEventParams) error
}

var _ Querier = (*Queries)(nil)
