// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package sqlcgen

import (
	"context"
)

const getEvent = `-- name: GetEvent :one
SELECT event_json FROM events WHERE event_id = ?
`

func (q *Queries) GetEvent(ctx context.Context, eventID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getEvent, eventID)
	var event_json string
	err := row.Scan(&event_json)
	return event_json, err
}

const getLastScan = `-- name: GetLastScan :one
SELECT last_scan FROM scan_meta WHERE provider = ?
`

func (q *Queries) GetLastScan(ctx context.Context, provider string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLastScan, provider)
	var last_scan int64
	err := row.Scan(&last_scan)
	return last_scan, err
}

const listEvents = `-- name: ListEvents :many
SELECT event_json FROM events
WHERE (?1 IS NULL OR provider = ?1)
  AND (?2     IS NULL OR repo = ?2)
  AND (?3    IS NULL OR ts_start_unixnano >= ?3)
  AND (?4    IS NULL OR ts_start_unixnano <= ?4)
ORDER BY ts_start_unixnano ASC
`

type ListEventsParams struct {
	Provider interface{}
	Repo     interface{}
	Since    interface{}
	Until    interface{}
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listEvents,
		arg.Provider,
		arg.Repo,
		arg.Since,
		arg.Until,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var event_json string
		if err := rows.Scan(&event_json); err != nil {
			return nil, err
		}
		items = append(items, event_json)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLastScan = `-- name: SetLastScan :exec
INSERT INTO scan_meta (provider, last_scan) VALUES (?, ?)
ON CONFLICT(provider) DO UPDATE SET last_scan = excluded.last_scan
`

type SetLastScanParams struct {
	Provider string
	LastScan int64
}

func (q *Queries) SetLastScan(ctx context.Context, arg SetLastScanParams) error {
	_, err := q.db.ExecContext(ctx, setLastScan, arg.Provider, arg.LastScan)
	return err
}

const upsertEvent = `-- name: UpsertEvent :exec
INSERT INTO events (
  event_id, schema_version, provider, surface, repo, project, cost_tag, model, ts_start_unixnano, event_json
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(event_id) DO UPDATE SET
  schema_version    = excluded.schema_version,
  provider          = excluded.provider,
  surface           = excluded.surface,
  repo              = excluded.repo,
  project           = excluded.project,
  cost_tag          = excluded.cost_tag,
  model             = excluded.model,
  ts_start_unixnano = excluded.ts_start_unixnano,
  event_json        = excluded.event_json
`

type UpsertEventParams struct {
	EventID         string
	SchemaVersion   int64
	Provider        string
	Surface         string
	Repo            string
	Project         string
	CostTag         string
	Model           string
	TsStartUnixnano int64
	EventJson       string
}

func (q *Queries) UpsertEvent(ctx context.Context, arg UpsertEventParams) error {
	_, err := q.db.ExecContext(ctx, upsertEvent,
		arg.EventID,
		arg.SchemaVersion,
		arg.Provider,
		arg.Surface,
		arg.Repo,
		arg.Project,
		arg.CostTag,
		arg.Model,
		arg.TsStartUnixnano,
		arg.EventJson,
	)
	return err
}
