//go:build sqlite

// SQLite-backed Store (optional backend, build with -tags sqlite). Queries
// are generated by sqlc from internal/store/sql/*.sql into internal/store/sqlcgen
// (regenerate with `sqlc generate`), so the SQL is type-checked at build time.
// Runtime needs the pure-Go modernc.org/sqlite driver — run `go get
// modernc.org/sqlite` on a machine with module access. The default 0A build uses
// the zero-dependency FileStore; both satisfy the same Store contract. This backend
// is the multi-writer-safe store (cross-process locking + transactional upserts) the
// daemon's concurrency note points to — opt in once a background scanner shares the
// ledger with manual invocations.
//
// See design-documents/02-data-model.md §6.
package store

import (
	"context"
	"database/sql"
	_ "embed"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/cloudyali/ai-agent-spend/internal/event"
	"github.com/cloudyali/ai-agent-spend/internal/store/sqlcgen"

	_ "modernc.org/sqlite" // registers the pure-Go "sqlite" driver
)

//go:embed sql/schema.sql
var sqliteSchema string

var _ Store = (*SQLiteStore)(nil)

// SQLiteStore persists events to a local SQLite database via sqlc-generated queries.
type SQLiteStore struct {
	db  *sql.DB
	q   *sqlcgen.Queries
	ctx context.Context
}

// OpenSQLite opens (creating if needed) the database at path and ensures schema.
func OpenSQLite(path string) (*SQLiteStore, error) {
	db, err := sql.Open("sqlite", path)
	if err != nil {
		return nil, fmt.Errorf("store: open sqlite: %w", err)
	}
	db.SetMaxOpenConns(1) // single writer keeps modernc/sqlite simple
	if _, err := db.Exec(sqliteSchema); err != nil {
		_ = db.Close()
		return nil, fmt.Errorf("store: apply schema: %w", err)
	}
	return &SQLiteStore{db: db, q: sqlcgen.New(db), ctx: context.Background()}, nil
}

// Close releases the database handle.
func (s *SQLiteStore) Close() error { return s.db.Close() }

// Upsert writes events idempotently (ON CONFLICT on event_id) in one transaction.
func (s *SQLiteStore) Upsert(events []event.AgentEvent) error {
	tx, err := s.db.BeginTx(s.ctx, nil)
	if err != nil {
		return fmt.Errorf("store: begin: %w", err)
	}
	defer func() { _ = tx.Rollback() }()

	q := s.q.WithTx(tx)
	for _, e := range events {
		if e.EventID == "" {
			return fmt.Errorf("store: refusing to persist event with empty EventID")
		}
		blob, err := json.Marshal(e)
		if err != nil {
			return fmt.Errorf("store: marshal %s: %w", e.EventID, err)
		}
		if err := q.UpsertEvent(s.ctx, sqlcgen.UpsertEventParams{
			EventID:         e.EventID,
			SchemaVersion:   int64(e.SchemaVersion),
			Provider:        e.Provider,
			Surface:         e.Surface,
			Repo:            e.Repo,
			Project:         e.Project,
			CostTag:         e.CostTag,
			Model:           e.Model,
			TsStartUnixnano: e.TSStart.UTC().UnixNano(),
			EventJson:       string(blob),
		}); err != nil {
			return fmt.Errorf("store: upsert %s: %w", e.EventID, err)
		}
	}
	return tx.Commit()
}

// Query returns events matching the filter, ordered by ts_start ascending.
func (s *SQLiteStore) Query(f Filter) ([]event.AgentEvent, error) {
	params := sqlcgen.ListEventsParams{}
	if f.Provider != "" {
		params.Provider = f.Provider
	}
	if f.Repo != "" {
		params.Repo = f.Repo
	}
	if !f.Since.IsZero() {
		params.Since = f.Since.UTC().UnixNano()
	}
	if !f.Until.IsZero() {
		params.Until = f.Until.UTC().UnixNano()
	}

	blobs, err := s.q.ListEvents(s.ctx, params)
	if err != nil {
		return nil, fmt.Errorf("store: query: %w", err)
	}
	out := make([]event.AgentEvent, 0, len(blobs))
	for _, b := range blobs {
		var e event.AgentEvent
		if err := json.Unmarshal([]byte(b), &e); err != nil {
			return nil, fmt.Errorf("store: decode row: %w", err)
		}
		out = append(out, e)
	}
	return out, nil
}

// Get returns one event by ID, or an error if absent.
func (s *SQLiteStore) Get(eventID string) (event.AgentEvent, error) {
	blob, err := s.q.GetEvent(s.ctx, eventID)
	if errors.Is(err, sql.ErrNoRows) {
		return event.AgentEvent{}, fmt.Errorf("store: event %q not found", eventID)
	}
	if err != nil {
		return event.AgentEvent{}, err
	}
	var e event.AgentEvent
	if err := json.Unmarshal([]byte(blob), &e); err != nil {
		return event.AgentEvent{}, fmt.Errorf("store: decode %s: %w", eventID, err)
	}
	return e, nil
}

// LastScan returns the last scan time for a provider (zero if never scanned).
func (s *SQLiteStore) LastScan(provider string) (time.Time, error) {
	nanos, err := s.q.GetLastScan(s.ctx, provider)
	if errors.Is(err, sql.ErrNoRows) || nanos == 0 {
		return time.Time{}, nil
	}
	if err != nil {
		return time.Time{}, err
	}
	return time.Unix(0, nanos).UTC(), nil
}

// SetLastScan records the last scan time for a provider.
func (s *SQLiteStore) SetLastScan(provider string, t time.Time) error {
	return s.q.SetLastScan(s.ctx, sqlcgen.SetLastScanParams{
		Provider: provider,
		LastScan: t.UTC().UnixNano(),
	})
}
